/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión (UC-01)
         * @description Valida credenciales y devuelve un access token JWT. El refresh token se entrega en una cookie httpOnly.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Autenticación correcta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /**
                 * @description Autenticación fallida. Cubre tanto **credenciales inválidas** como **cuenta
                 *     deshabilitada** (`activo=false`) con idéntico cuerpo de error (decisión
                 *     anti-enumeration deliberada). El cliente no puede distinguir ambos casos.
                 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar access token
         * @description Usa el refresh token de la cookie httpOnly para emitir un nuevo access token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nuevo access token emitido */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión (UC-02)
         * @description Invalida el refresh token y limpia la cookie de sesión.
         *     [F1-09] Se autentica con la cookie de refresh (no con el access token), para permitir
         *     el logout aunque el access token ya haya expirado (US-002).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesión cerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuario autenticado
         * @description [F1-08] Soporte de restauración de sesión del shell (US-000A/US-001).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Datos del usuario en sesión */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reservas (pipeline)
         * @description Lista paginada de reservas del tenant con filtros por estado, sub-estado, fecha y canal.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Número de página */
                    page?: components["parameters"]["Page"];
                    /** @description Elementos por página */
                    limit?: components["parameters"]["Limit"];
                    estado?: components["schemas"]["EstadoReserva"];
                    subEstado?: components["schemas"]["SubEstadoConsulta"];
                    fechaDesde?: string;
                    fechaHasta?: string;
                    /** @description Búsqueda por código, nombre de cliente o notas */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reservas recuperadas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservaListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Dar de alta un nuevo lead/consulta (UC-03)
         * @description Crea una reserva en estado `consulta`. Sin `fechaEvento` (US-003, alta exploratoria) la
         *     reserva nace en sub-estado `2a` con `ttlExpiracion = null` y SIN crear `FechaBloqueada`;
         *     con `fechaEvento` nace en `2b` (US-004/005, dispara el bloqueo blando atómico).
         *     El CLIENTE se crea/reutiliza de forma idempotente por `(tenant_id, email)`. El campo
         *     `comentarios` decide el flujo del email E1 (ver su descripción en `CreateReservaRequest`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReservaRequest"];
                };
            };
            responses: {
                /**
                 * @description Reserva creada. En el alta exploratoria sin fecha (US-003) el recurso devuelto tiene
                 *     `estado = 'consulta'`, `subEstado = '2a'` y `ttlExpiracion = null`.
                 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
                400: components["responses"]["ValidationError"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        /** Detalle de reserva */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reserva recuperada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservaDetalle"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar datos de la reserva
         * @description Actualización parcial de los campos editables (invitados, duración, tipo de evento, notas…).
         *     No cambia el estado. [F1-07] El nº de invitados (US-007) y datos núcleo del lead; la fecha de
         *     evento NO se asigna aquí sino vía /transiciones (ver [F1-01]).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateReservaRequest"];
                };
            };
            responses: {
                /** @description Reserva actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/reservas/{id}/transiciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ejecutar una transición de estado (UC-04, UC-06, UC-10, UC-23, UC-25, UC-28)
         * @description Aplica una transición de la máquina de estados de la reserva. El backend valida la
         *     transición contra la tabla declarativa de transiciones y sus guardas. Cubre, entre otras:
         *     2.a→2.b (asignar fecha), 2.b→2.c (pendiente invitados), →2.z (descartar por cliente),
         *     iniciar evento, finalizar evento y archivar.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransicionRequest"];
                };
            };
            responses: {
                /** @description Transición aplicada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
                409: components["responses"]["Conflict"];
                /** @description Transición no permitida o guarda no satisfecha */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/extender-bloqueo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extender plazo de bloqueo (UC-05)
         * @description Amplía el `ttl_expiracion` del bloqueo blando vigente según la política del tenant.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bloqueo extendido */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/visita": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Programar visita al espacio (UC-07)
         * @description Transiciona la consulta a sub-estado `2.v` y fija fecha/hora de visita.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProgramarVisitaRequest"];
                };
            };
            responses: {
                /** @description Visita programada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** Registrar resultado de visita (UC-08) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResultadoVisitaRequest"];
                };
            };
            responses: {
                /** @description Resultado registrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/reservas/{id}/cola": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        /** Visualizar cola de espera de la fecha de una reserva bloqueante (UC-11) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cola FIFO ordenada por posición */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ColaItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/promover": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promover consulta de la cola (UC-12)
         * @description Promueve la primera consulta en cola (2.d→2.b) cuando la bloqueante se libera. Encadenamiento automático.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consulta promovida */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/salir-cola": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Salir voluntariamente de la cola (UC-13) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reserva retirada de la cola */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tarifas/calcular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calcular tarifa según configuración (UC-16 / US-016)
         * @description Motor de tarifa (US-016, lectura pura, multi-tenant por JWT). Determina la temporada del mes de `fecha_evento`, busca la TARIFA vigente por temporada x duración x tramo de invitados y suma los extras del catálogo del tenant. Devuelve el esquema canónico D-1. Con `num_adultos_ninos_mayores4 > 50` responde 200 con `tarifa_a_consultar: true` e importes `null` (precio manual), SIN error.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CalculoTarifaRequest"];
                };
            };
            responses: {
                /** @description Tarifa calculada (caso normal) o tarifa a consultar (>50 invitados): mismo esquema canónico. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalculoTarifaResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description EXTRA_NO_ENCONTRADO: un extra no existe, está inactivo o no es visible en el tenant (RLS). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalculoTarifaExtraNoEncontradoError"];
                    };
                };
                /** @description Configuración incompleta del tarifario: `TARIFA_NO_CONFIGURADA` (sin TARIFA vigente para una combinación válida con <= 50 invitados) o `TEMPORADA_NO_CONFIGURADA` (mes sin mapear en TEMPORADA_CALENDARIO). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalculoTarifaTarifaNoConfiguradaError"] | components["schemas"]["CalculoTarifaTemporadaNoConfiguradaError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar catálogo de extras del tenant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catálogo de extras configurables */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Extra"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/presupuestos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        /** Listar versiones de presupuesto de la reserva */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Presupuestos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Presupuesto"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Generar presupuesto y activar pre-reserva (UC-14)
         * @description Crea una nueva versión de presupuesto (PDF), congela la tarifa y transiciona la reserva a `pre_reserva` (bloqueo firme/7 días).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePresupuestoRequest"];
                };
            };
            responses: {
                /** @description Presupuesto generado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Presupuesto"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presupuestos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del recurso */
                id: components["parameters"]["IdGenerico"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar y enviar presupuesto (UC-15)
         * @description Edita líneas/descuento y, opcionalmente, marca el presupuesto como `enviado` (dispara email E-presupuesto).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identificador del recurso */
                    id: components["parameters"]["IdGenerico"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePresupuestoRequest"];
                };
            };
            responses: {
                /** @description Presupuesto actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Presupuesto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/reservas/{id}/extras": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        /** Listar extras de la reserva */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Extras de la reserva */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservaExtra"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Añadir extra a la reserva (UC-14, UC-21)
         * @description Añade una línea de extra con precio congelado. `origen` indica si viene del presupuesto o se añade tras la confirmación.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReservaExtraRequest"];
                };
            };
            responses: {
                /** @description Extra añadido */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservaExtra"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/pagos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar pago de señal / registrar cobro (UC-17, UC-21, UC-22)
         * @description Registra un `Pago` conciliado contra una factura. El pago de señal transiciona la reserva a `reserva_confirmada` (bloqueo firme).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePagoRequest"];
                };
            };
            responses: {
                /** @description Pago registrado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pago"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/facturas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        /** Listar facturas de la reserva */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Facturas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Factura"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Generar factura (UC-18, UC-21)
         * @description Emite una factura en estado `borrador` (`senal`, `liquidacion`, `fianza` o `complementaria`). La liquidación arrastra los `ReservaExtra` con `factura_id` nulo.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFacturaRequest"];
                };
            };
            responses: {
                /** @description Factura generada (borrador) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Factura"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/facturas/{facturaId}/enviar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
                /** @description ID de la factura */
                facturaId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprobar y enviar factura (UC-28)
         * @description Transiciona la factura `borrador → enviada`, asigna número de factura y dispara el email E4.
         *     Para la liquidación, su envío es prerequisito del cobro y arrastra el efecto sobre `fianza_status`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                    /** @description ID de la factura */
                    facturaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Factura aprobada y enviada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Factura"];
                    };
                };
                409: components["responses"]["Conflict"];
                /** @description La factura no está en estado `borrador` */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/condiciones-particulares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gestionar condiciones particulares (UC-19)
         * @description Marca el envío o la firma de las condiciones particulares y asocia el documento firmado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CondicionesParticularesRequest"];
                };
            };
            responses: {
                /** @description Estado de condiciones actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/subprocesos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Gestionar sub-procesos paralelos (UC-20, UC-21, UC-22)
         * @description Avanza el estado de los sub-procesos `pre_evento`, `liquidacion` y/o `fianza`.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubprocesosRequest"];
                };
            };
            responses: {
                /** @description Sub-procesos actualizados */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/reservas/{id}/fianza/devolver": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Procesar devolución de fianza (UC-27)
         * @description Registra la devolución total o parcial (retención por desperfectos) de la fianza.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DevolucionFianzaRequest"];
                };
            };
            responses: {
                /** @description Devolución procesada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reserva"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/ficha-operativa": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        /** Consultar ficha operativa del evento (UC-24) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ficha operativa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FichaOperativa"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Crear/actualizar ficha operativa (UC-20, UC-24) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertFichaOperativaRequest"];
                };
            };
            responses: {
                /** @description Ficha guardada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FichaOperativa"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar calendario y disponibilidad (UC-29)
         * @description Devuelve reservas y fechas bloqueadas del tenant en un rango, para las vistas mensual/semanal.
         */
        get: {
            parameters: {
                query: {
                    desde: string;
                    hasta: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disponibilidad del rango */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarioItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fechas-bloqueadas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bloquear fecha (UC-30)
         * @description Operación crítica. Crea un `FechaBloqueada` dentro de una transacción con
         *     `SELECT ... FOR UPDATE`. La restricción `UNIQUE(tenant_id, fecha)` garantiza
         *     que dos peticiones concurrentes para la misma fecha resulten en un éxito y un 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BloquearFechaRequest"];
                };
            };
            responses: {
                /** @description Fecha bloqueada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FechaBloqueada"];
                    };
                };
                /** @description La fecha ya está bloqueada (doble reserva evitada) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fechas-bloqueadas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del recurso */
                id: components["parameters"]["IdGenerico"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Liberar fecha (UC-31)
         * @description Libera la fecha y dispara la promoción de la cola de espera si la hay.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identificador del recurso */
                    id: components["parameters"]["IdGenerico"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fecha liberada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del recurso */
                id: components["parameters"]["IdGenerico"];
            };
            cookie?: never;
        };
        /** Detalle de cliente (soporte, US-014) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identificador del recurso */
                    id: components["parameters"]["IdGenerico"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cliente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cliente"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar datos fiscales / IBAN del cliente (US-035) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identificador del recurso */
                    id: components["parameters"]["IdGenerico"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateClienteRequest"];
                };
            };
            responses: {
                /** @description Cliente actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cliente"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/historico/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar en histórico (UC-32)
         * @description Búsqueda full-text sobre reservas archivadas (código, cliente, notas).
         */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    /** @description Número de página */
                    page?: components["parameters"]["Page"];
                    /** @description Elementos por página */
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resultados del histórico */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservaListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/historico/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar reservas (UC-33)
         * @description Exporta el histórico filtrado a CSV.
         */
        get: {
            parameters: {
                query?: {
                    fechaDesde?: string;
                    fechaHasta?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fichero CSV */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Visualizar dashboard operativo (UC-34)
         * @description Devuelve KPIs operativos (ocupación, conversión, pipeline) y financieros (ingresos, cobros pendientes).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KPIs del dashboard */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/comunicaciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la reserva */
                id: components["parameters"]["IdReserva"];
            };
            cookie?: never;
        };
        /** Log de comunicaciones de la reserva */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comunicaciones */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comunicacion"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Enviar email manual o automático (UC-35, UC-36)
         * @description Crea y envía (o guarda como borrador para revisión, UC-36) un email vinculado a la reserva.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la reserva */
                    id: components["parameters"]["IdReserva"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateComunicacionRequest"];
                };
            };
            responses: {
                /** @description Comunicación creada/enviada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comunicacion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subir documento (UC-19, UC-24)
         * @description Sube un documento polimórfico (DNI, cláusula, condiciones, justificante de pago, etc.) al storage y registra sus metadatos.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        tipo: components["schemas"]["TipoDocumento"];
                        /** Format: uuid */
                        reservaId?: string;
                    };
                };
            };
            responses: {
                /** @description Documento subido */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Documento"];
                    };
                };
                /** @description Tipo de fichero no válido o demasiado grande (>10MB) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cron/barrido": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Barrido periódico de TTLs, cola y recordatorios
         * @description Endpoint protegido (token de servicio) invocado por el cron. Es idempotente:
         *     barre reservas con `ttl_expiracion` vencido, las expira (2.b→2.x), libera la fecha,
         *     promueve la cola y dispara recordatorios automáticos. No depende del reloj exacto.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Barrido concreto a ejecutar (por defecto todos) */
                    tarea?: "expiracion" | "cola" | "fichas" | "eventos" | "archivado" | "recordatorios" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Barrido ejecutado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BarridoResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Importe monetario en EUR, Decimal(10,2) serializado como string para evitar coma flotante.
         * @example 1234.56
         */
        Importe: string;
        /**
         * @description Porcentaje, Decimal(4,2) serializado como string.
         * @example 21.00
         */
        Porcentaje: string;
        /** @enum {string} */
        EstadoReserva: "consulta" | "pre_reserva" | "reserva_confirmada" | "evento_en_curso" | "post_evento" | "reserva_completada" | "reserva_cancelada";
        /** @enum {string} */
        SubEstadoConsulta: "2a" | "2b" | "2c" | "2d" | "2v" | "2x" | "2y" | "2z";
        /** @enum {string} */
        CanalEntrada: "web" | "email" | "whatsapp" | "instagram" | "telefono";
        /** @enum {integer} */
        DuracionHoras: 4 | 8 | 12;
        /** @enum {string} */
        TipoEvento: "boda" | "corporativo" | "privado" | "otro";
        /** @enum {string} */
        Temporada: "alta" | "media" | "baja";
        /** @enum {string} */
        TipoBloqueo: "blando" | "firme";
        /** @enum {string} */
        OrigenExtra: "presupuesto" | "anadido_post_confirmacion";
        /** @enum {string} */
        TipoFactura: "senal" | "liquidacion" | "fianza" | "complementaria";
        /** @enum {string} */
        EstadoPresupuesto: "borrador" | "enviado" | "aceptado" | "rechazado";
        /** @enum {string} */
        EstadoFactura: "borrador" | "enviada" | "cobrada";
        /** @enum {string} */
        FianzaStatus: "pendiente" | "recibo_enviado" | "cobrada" | "devuelta" | "retenida_parcial";
        /** @enum {string} */
        PreEventoStatus: "pendiente" | "en_curso" | "cerrado";
        /** @enum {string} */
        LiquidacionStatus: "pendiente" | "facturada" | "cobrada";
        /** @enum {string} */
        TipoDocumento: "dni_anverso" | "dni_reverso" | "clausula_responsabilidad" | "condiciones_particulares" | "justificante_pago" | "presupuesto" | "factura" | "otro";
        /** @enum {string} */
        CodigoEmail: "E1" | "E2" | "E3" | "E4" | "E5" | "E6" | "E7" | "E8" | "manual";
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description JWT de vida corta (~15 min) */
            accessToken: string;
            usuario: components["schemas"]["Usuario"];
        };
        Usuario: {
            /** Format: uuid */
            idUsuario?: string;
            /** Format: email */
            email?: string;
            nombre?: string;
            apellidos?: string | null;
            /** @enum {string} */
            rol?: "gestor" | "admin" | "operario";
        };
        Reserva: {
            /** Format: uuid */
            idReserva: string;
            /** @example SLO-2026-0001 */
            codigo: string;
            /** Format: uuid */
            clienteId: string;
            estado: components["schemas"]["EstadoReserva"];
            subEstado?: components["schemas"]["SubEstadoConsulta"];
            canalEntrada: components["schemas"]["CanalEntrada"];
            /** Format: date */
            fechaEvento?: string | null;
            duracionHoras?: components["schemas"]["DuracionHoras"] | null;
            tipoEvento?: components["schemas"]["TipoEvento"] | null;
            numAdultosNinosMayores4?: number | null;
            numNinosMenores4?: number | null;
            numInvitadosFinal?: number | null;
            importeTotal?: components["schemas"]["Importe"] | null;
            importeSenal?: components["schemas"]["Importe"] | null;
            importeLiquidacion?: components["schemas"]["Importe"] | null;
            /** Format: date-time */
            ttlExpiracion?: string | null;
            /** Format: date */
            visitaProgramadaFecha?: string | null;
            /** @example 17:30 */
            visitaProgramadaHora?: string | null;
            visitaRealizada?: boolean | null;
            fianzaEur?: components["schemas"]["Importe"] | null;
            /** Format: date */
            fianzaCobradaFecha?: string | null;
            /** Format: date */
            fianzaDevueltaFecha?: string | null;
            fianzaDevueltaEur?: components["schemas"]["Importe"] | null;
            condPartFirmadas?: boolean | null;
            /** Format: date-time */
            condPartFechaEnvio?: string | null;
            /** Format: date-time */
            condPartFechaFirma?: string | null;
            preEventoStatus?: components["schemas"]["PreEventoStatus"];
            liquidacionStatus?: components["schemas"]["LiquidacionStatus"];
            fianzaStatus?: components["schemas"]["FianzaStatus"];
            posicionCola?: number | null;
            /** Format: uuid */
            consultaBloqueanteId?: string | null;
            notas?: string | null;
            /** Format: date-time */
            fechaCreacion?: string;
        };
        ReservaDetalle: components["schemas"]["Reserva"] & {
            cliente?: components["schemas"]["Cliente"];
            extras?: components["schemas"]["ReservaExtra"][];
            presupuestos?: components["schemas"]["Presupuesto"][];
            facturas?: components["schemas"]["Factura"][];
        };
        ReservaListResponse: {
            data: components["schemas"]["Reserva"][];
            metadata: components["schemas"]["PaginationMetadata"];
        };
        CreateReservaRequest: {
            canalEntrada: components["schemas"]["CanalEntrada"];
            /**
             * Format: date
             * @description Si se envía, se crea en sub-estado 2.b con bloqueo blando
             */
            fechaEvento?: string | null;
            tipoEvento?: components["schemas"]["TipoEvento"];
            duracionHoras?: components["schemas"]["DuracionHoras"];
            numAdultosNinosMayores4?: number;
            numNinosMenores4?: number;
            notas?: string;
            /** @description [US-003] Comentarios libres del gestor sobre el lead en el momento del alta. Su PRESENCIA/AUSENCIA decide el flujo del email E1 (respuesta inicial automática): SIN `comentarios` (omitido o vacío) → la COMUNICACION E1 se persiste con `estado='enviado'` y se dispara el auto-envío de la respuesta inicial; CON `comentarios` → la COMUNICACION E1 se persiste con `estado='borrador'`, NO se envía, y la UI alerta al gestor de un borrador pendiente de revisión. Es distinto de `notas` (anotaciones internas que NO afectan al envío de E1). */
            comentarios?: string;
            cliente: components["schemas"]["CreateClienteRequest"];
        };
        UpdateReservaRequest: {
            tipoEvento?: components["schemas"]["TipoEvento"];
            duracionHoras?: components["schemas"]["DuracionHoras"];
            numAdultosNinosMayores4?: number;
            numNinosMenores4?: number;
            numInvitadosFinal?: number;
            notas?: string;
        };
        TransicionRequest: {
            estadoDestino: components["schemas"]["EstadoReserva"];
            subEstadoDestino?: components["schemas"]["SubEstadoConsulta"];
            /**
             * Format: date
             * @description Obligatorio en la transición 2.a→2.b (US-005): asigna la fecha y dispara el bloqueo atómico.
             */
            fechaEvento?: string | null;
            /** @description Obligatorio en cancelaciones/descartes */
            motivo?: string;
        };
        ProgramarVisitaRequest: {
            /** Format: date */
            visitaFecha: string;
            /** @example 17:30 */
            visitaHora: string;
        };
        ResultadoVisitaRequest: {
            visitaRealizada: boolean;
            notas?: string;
        };
        ColaItem: {
            /** Format: uuid */
            idReserva?: string;
            codigo?: string;
            posicionCola?: number;
            clienteNombre?: string;
        };
        Cliente: {
            /** Format: uuid */
            idCliente: string;
            nombre: string;
            apellidos?: string | null;
            /** Format: email */
            email?: string | null;
            telefono?: string | null;
            dniNif?: string | null;
            direccion?: string | null;
            codigoPostal?: string | null;
            poblacion?: string | null;
            provincia?: string | null;
            ibanDevolucion?: string | null;
        };
        CreateClienteRequest: {
            /** @description Obligatorio, no vacío, máx 100. */
            nombre: string;
            /** @description Obligatorio, no vacío, máx 100. */
            apellidos: string;
            /**
             * Format: email
             * @description Obligatorio. Formato email RFC 5322 básico. Idempotencia de CLIENTE por (tenant_id, email).
             */
            email: string;
            /** @description Obligatorio, no vacío. */
            telefono: string;
            dniNif?: string;
            direccion?: string;
            codigoPostal?: string;
            poblacion?: string;
            provincia?: string;
        };
        UpdateClienteRequest: {
            nombre?: string;
            apellidos?: string;
            /** Format: email */
            email?: string;
            telefono?: string;
            dniNif?: string;
            direccion?: string;
            codigoPostal?: string;
            poblacion?: string;
            provincia?: string;
            ibanDevolucion?: string;
        };
        Extra: {
            /** Format: uuid */
            idExtra?: string;
            nombre?: string;
            descripcion?: string | null;
            precioUnitario?: components["schemas"]["Importe"];
            activo?: boolean;
        };
        CalculoTarifaExtraInput: {
            /**
             * Format: uuid
             * @description ID del EXTRA del catálogo del tenant.
             */
            extra_id: string;
            /** @description Unidades del extra (>= 1). */
            cantidad: number;
        };
        CalculoTarifaRequest: {
            /**
             * Format: date
             * @description Fecha del evento (YYYY-MM-DD). Debe ser estrictamente futura: no nula, no pasada y no el mismo día que la llamada (comparación por día natural UTC).
             */
            fecha_evento: string;
            duracion_horas: components["schemas"]["DuracionHoras"];
            /** @description Adultos + niños mayores de 4 años. Los menores de 4 (num_ninos_menores4) no cuentan ni se pasan. */
            num_adultos_ninos_mayores4: number;
            /**
             * @description Extras a sumar. Puede ser []. Solo se evalúan en el caso normal (no en tarifa_a_consultar).
             * @default []
             */
            extras: components["schemas"]["CalculoTarifaExtraInput"][];
        };
        CalculoTarifaResponse: {
            /** @description Temporada resuelta para el mes de fecha_evento. SIEMPRE presente (también en a_consultar). */
            temporada: components["schemas"]["Temporada"];
            /** @description true cuando num_adultos_ninos_mayores4 > 50 (tramo +51 sin tarifa): precio manual. SIEMPRE presente. */
            tarifa_a_consultar: boolean;
            /** @description Precio de la TARIFA en EUR (IVA 21% incluido). null si tarifa_a_consultar=true. */
            precio_tarifa_eur: number | null;
            /** @description Suma de subtotales de extras (precio_eur x cantidad). null si tarifa_a_consultar=true. */
            extras_total_eur: number | null;
            /** @description precio_tarifa_eur + extras_total_eur. null si tarifa_a_consultar=true. */
            total_eur: number | null;
            /**
             * Format: uuid
             * @description ID de la fila TARIFA usada. null si tarifa_a_consultar=true.
             */
            tarifa_id: string | null;
        };
        CalculoTarifaTarifaNoConfiguradaError: components["schemas"]["ErrorResponse"] & {
            /** @enum {string} */
            codigo: "TARIFA_NO_CONFIGURADA";
            /** @description Parámetros de búsqueda sin fila de TARIFA vigente (tarifario incompleto, num_invitados <= 50). */
            detalle: {
                temporada: components["schemas"]["Temporada"];
                duracion_horas: components["schemas"]["DuracionHoras"];
                num_invitados: number;
            };
        };
        CalculoTarifaExtraNoEncontradoError: components["schemas"]["ErrorResponse"] & {
            /** @enum {string} */
            codigo: "EXTRA_NO_ENCONTRADO";
            detalle: {
                /** Format: uuid */
                extra_id: string;
                /**
                 * @description Motivo. El extra de otro tenant (RLS) se reporta como `inexistente` para no filtrar su existencia.
                 * @enum {string}
                 */
                motivo: "inexistente" | "inactivo";
            };
        };
        CalculoTarifaTemporadaNoConfiguradaError: components["schemas"]["ErrorResponse"] & {
            /** @enum {string} */
            codigo: "TEMPORADA_NO_CONFIGURADA";
            detalle: {
                /** @description Mes (1-12) sin fila en TEMPORADA_CALENDARIO del tenant. */
                mes: number;
            };
        };
        Presupuesto: {
            /** Format: uuid */
            idPresupuesto?: string;
            /** Format: uuid */
            reservaId?: string;
            version?: number;
            baseImponible?: components["schemas"]["Importe"];
            ivaPorcentaje?: components["schemas"]["Porcentaje"];
            ivaImporte?: components["schemas"]["Importe"];
            total?: components["schemas"]["Importe"];
            descuentoEur?: components["schemas"]["Importe"] | null;
            descuentoMotivo?: string | null;
            pdfUrl?: string | null;
            estado?: components["schemas"]["EstadoPresupuesto"];
            /** Format: date-time */
            fechaEnvio?: string | null;
        };
        CreatePresupuestoRequest: {
            descuentoEur?: components["schemas"]["Importe"];
            descuentoMotivo?: string;
            extras?: components["schemas"]["CreateReservaExtraRequest"][];
        };
        UpdatePresupuestoRequest: {
            descuentoEur?: components["schemas"]["Importe"];
            descuentoMotivo?: string;
            /** @description Si true, marca como enviado y dispara el email */
            enviar?: boolean;
        };
        ReservaExtra: {
            /** Format: uuid */
            idReservaExtra?: string;
            /** Format: uuid */
            reservaId?: string;
            /** Format: uuid */
            extraId?: string | null;
            /** Format: uuid */
            facturaId?: string | null;
            conceptoLibre?: string | null;
            origen?: components["schemas"]["OrigenExtra"];
            cantidad?: number;
            precioUnitario?: components["schemas"]["Importe"];
            subtotal?: components["schemas"]["Importe"];
        };
        CreateReservaExtraRequest: {
            /** Format: uuid */
            extraId?: string | null;
            /** @description Para extras fuera de catálogo */
            conceptoLibre?: string;
            cantidad: number;
            origen: components["schemas"]["OrigenExtra"];
            /** @description Obligatorio si extraId es nulo */
            precioUnitario?: components["schemas"]["Importe"];
        };
        Factura: {
            /** Format: uuid */
            idFactura?: string;
            /** Format: uuid */
            reservaId?: string;
            /**
             * @description Asignado al enviar (borrador no tiene número)
             * @example F-2026-0001
             */
            numeroFactura?: string | null;
            tipo?: components["schemas"]["TipoFactura"];
            baseImponible?: components["schemas"]["Importe"];
            ivaPorcentaje?: components["schemas"]["Porcentaje"];
            ivaImporte?: components["schemas"]["Importe"];
            total?: components["schemas"]["Importe"];
            concepto?: string | null;
            pdfUrl?: string | null;
            estado?: components["schemas"]["EstadoFactura"];
            /** Format: date-time */
            fechaEmision?: string | null;
        };
        CreateFacturaRequest: {
            tipo: components["schemas"]["TipoFactura"];
            concepto?: string;
        };
        Pago: {
            /** Format: uuid */
            idPago?: string;
            /** Format: uuid */
            facturaId?: string;
            importe?: components["schemas"]["Importe"];
            /** Format: date */
            fechaCobro?: string;
            /** Format: uuid */
            justificanteDocId?: string | null;
        };
        CreatePagoRequest: {
            /** Format: uuid */
            facturaId: string;
            importe: components["schemas"]["Importe"];
            /** Format: date */
            fechaCobro: string;
            /** Format: uuid */
            justificanteDocId?: string | null;
        };
        CondicionesParticularesRequest: {
            /** @enum {string} */
            accion: "enviar" | "marcar_firmadas";
            /**
             * Format: uuid
             * @description Documento firmado, en marcar_firmadas
             */
            documentoId?: string;
        };
        SubprocesosRequest: {
            preEventoStatus?: components["schemas"]["PreEventoStatus"];
            liquidacionStatus?: components["schemas"]["LiquidacionStatus"];
            fianzaStatus?: components["schemas"]["FianzaStatus"];
        };
        DevolucionFianzaRequest: {
            /** @description Menor que fianza_eur si hay retención parcial */
            importeDevuelto: components["schemas"]["Importe"];
            motivoRetencion?: string;
        };
        FichaOperativa: {
            /** Format: uuid */
            idFicha?: string;
            /** Format: uuid */
            reservaId?: string;
            numInvitadosConfirmado?: number | null;
            menuSeleccionado?: string | null;
            timingDetallado?: string | null;
            contactoEventoNombre?: string | null;
            contactoEventoTelefono?: string | null;
            notasOperativas?: string | null;
            briefingEquipo?: string | null;
            fichaCerrada?: boolean;
        };
        UpsertFichaOperativaRequest: {
            numInvitadosConfirmado?: number;
            menuSeleccionado?: string;
            timingDetallado?: string;
            contactoEventoNombre?: string;
            contactoEventoTelefono?: string;
            notasOperativas?: string;
            briefingEquipo?: string;
            fichaCerrada?: boolean;
        };
        CalendarioItem: {
            /** Format: date */
            fecha?: string;
            /** Format: uuid */
            reservaId?: string | null;
            codigo?: string | null;
            estado?: components["schemas"]["EstadoReserva"];
            tipoBloqueo?: components["schemas"]["TipoBloqueo"] | null;
        };
        FechaBloqueada: {
            /** Format: uuid */
            idBloqueo?: string;
            /** Format: date */
            fecha?: string;
            /** Format: uuid */
            reservaId?: string;
            tipoBloqueo?: components["schemas"]["TipoBloqueo"];
            /** Format: date-time */
            ttlExpiracion?: string | null;
        };
        BloquearFechaRequest: {
            /** Format: date */
            fecha: string;
            /** Format: uuid */
            reservaId: string;
            tipoBloqueo: components["schemas"]["TipoBloqueo"];
        };
        Comunicacion: {
            /** Format: uuid */
            idComunicacion?: string;
            /** Format: uuid */
            reservaId?: string | null;
            /** Format: uuid */
            clienteId?: string;
            codigoEmail?: components["schemas"]["CodigoEmail"];
            asunto?: string;
            /** Format: email */
            destinatarioEmail?: string;
            /** @enum {string} */
            estado?: "borrador" | "enviado" | "fallido";
            /** Format: date-time */
            fechaEnvio?: string | null;
        };
        CreateComunicacionRequest: {
            codigoEmail: components["schemas"]["CodigoEmail"];
            /** Format: email */
            destinatarioEmail: string;
            asunto: string;
            cuerpo?: string;
            /** @description UC-36: guarda para revisión antes de enviar */
            guardarComoBorrador?: boolean;
        };
        Documento: {
            /** Format: uuid */
            idDocumento?: string;
            /** Format: uuid */
            reservaId?: string | null;
            tipo?: components["schemas"]["TipoDocumento"];
            nombreArchivo?: string;
            url?: string;
            mimeType?: string;
            tamanoBytes?: number | null;
        };
        DashboardResponse: {
            /**
             * Format: double
             * @description % de fechas ocupadas (métrica de display)
             */
            ocupacionMesActual?: number;
            /**
             * Format: double
             * @description consultas → reservas confirmadas (métrica de display)
             */
            tasaConversion?: number;
            /** @description reservas en consulta + pre_reserva */
            pipelineActivo?: number;
            ingresosMes?: components["schemas"]["Importe"];
            cobrosPendientes?: components["schemas"]["Importe"];
            ticketMedio?: components["schemas"]["Importe"];
        };
        BarridoResponse: {
            reservasExpiradas?: number;
            fechasLiberadas?: number;
            consultasPromovidas?: number;
            recordatoriosEnviados?: number;
        };
        PaginationMetadata: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        ErrorResponse: {
            /** @example 409 */
            statusCode: number;
            /** @description Mensaje(s) de error (formato de excepción de NestJS) */
            message: string | string[];
            /** @example Conflict */
            error?: string;
        };
    };
    responses: {
        /** @description No autenticado o token inválido */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso no encontrado en el tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Error de validación de entrada */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflicto de estado o de concurrencia (p. ej. fecha ya bloqueada) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Demasiadas peticiones (rate-limit excedido) */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Número de página */
        Page: number;
        /** @description Elementos por página */
        Limit: number;
        /** @description ID de la reserva */
        IdReserva: string;
        /** @description Identificador del recurso */
        IdGenerico: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
